version: '3.8'

services:
  postgres:
    image: postgres
    container_name: vinbrain-database
    restart: unless-stopped
    ports:
      - "5445:5432"
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vinbrain
      POSTGRES_USER: vinbrain
      POSTGRES_PASSWORD: vinbrain@2024
      PGDATA: /var/lib/postgresql/data/pgdata
 

networks:
  vmg:
    name: vinbrain
    driver: bridge